### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by jlqzzz** [yinjunbo/SSDA3D#1]
Hi, authors. Thanks for your great work.

Do you have exact date for releasing the code?

**Comment by ldkong1205** [comment]
Same question here.

**Comment by adv010** [comment]
Same question here. 
Also, are there experiments carried out on NuScenes -> Kitti /  Waymo -> Kitti as given in ST3D?

**Comment by lfxx** [comment]
Any updates here?

**Comment by YanWang-AI** [comment]
Sorry for this late response. We are preparing the codes currently and will release the codes before the conference holds.
