### ISSUE TITLE
Could you share the trained model？

### ISSUE THREAD

**Issue by sky-fly97** [yinjunbo/SSDA3D#2]
I didn't find your trained model, could you share them?

**Comment by jetpackfirstme** [comment]
I will upload four trained models (1%, 5%, 10%, 20) and update the readme later.

**Comment by YanWang-AI** [comment]
> I didn't find your trained model, could you share them?

I will upload four trained models (1%, 5%, 10%, 20) and update the readme later.

**Comment by sky-fly97** [comment]
> > I didn't find your trained model, could you share them?
> 
> I will upload four trained models (1%, 5%, 10%, 20) and update the readme later.

Thank you~  please also upload the corresponding waymo pre-trained model.

**Comment by YanWang-AI** [comment]
> > > I didn't find your trained model, could you share them?
> > 
> > 
> > I will upload four trained models (1%, 5%, 10%, 20) and update the readme later.
> 
> Thank you~ please also upload the corresponding waymo pre-trained model.

We just checked Waymo Dataset License Agreement(https://waymo.com/open/terms/) and are sorry that we can not provide the pretrained models, but you should achieve similar performance by training with the default configs. To access these pretrained models, please send us an email with your name, institute, a screenshot of the Waymo dataset registration confirmation mail, and your intended usage. Please send a second email if we don't get back to you in two days. Please note that Waymo open dataset is under a strict non-commercial license, so we are not allowed to share the model with you if it will use for any profit-oriented activities.

**Comment by sky-fly97** [comment]
> > > > I didn't find your trained model, could you share them?
> > > 
> > > 
> > > I will upload four trained models (1%, 5%, 10%, 20) and update the readme later.
> > 
> > 
> > Thank you~ please also upload the corresponding waymo pre-trained model.
> 
> We just checked Waymo Dataset License Agreement(https://waymo.com/open/terms/) and are sorry that we can not provide the pretrained models, but you should achieve similar performance by training with the default configs. To access these pretrained models, please send us an email with your name, institute, a screenshot of the Waymo dataset registration confirmation mail, and your intended usage. Please send a second email if we don't get back to you in two days. Please note that Waymo open dataset is under a strict non-commercial license, so we are not allowed to share the model with you if it will use for any profit-oriented activities.

No problem， what is your email address?

**Comment by YanWang-AI** [comment]
> > > > > I didn't find your trained model, could you share them?
> > > > 
> > > > 
> > > > I will upload four trained models (1%, 5%, 10%, 20) and update the readme later.
> > > 
> > > 
> > > Thank you~ please also upload the corresponding waymo pre-trained model.
> > 
> > 
> > We just checked Waymo Dataset License Agreement(https://waymo.com/open/terms/) and are sorry that we can not provide the pretrained models, but you should achieve similar performance by training with the default configs. To access these pretrained models, please send us an email with your name, institute, a screenshot of the Waymo dataset registration confirmation mail, and your intended usage. Please send a second email if we don't get back to you in two days. Please note that Waymo open dataset is under a strict non-commercial license, so we are not allowed to share the model with you if it will use for any profit-oriented activities.
> 
> No problem， what is your email address?

yanwang@bit.edu.cn
