### ISSUE TITLE
About the intra_domain_point_mixup

### ISSUE THREAD

**Issue by AGI-player** [yinjunbo/SSDA3D#3]
Hello, thanks for your great work. 
I found some differences between the code and paper. According to the paper,  "before merging the 3D boxes, collision detection will be performed". But in the intra_domain_point_mixup function, the  "gt_boxes" were  merged directly. This may cause some problems.

**Comment by jetpackfirstme** [comment]
> 

Thank you for your attention to the paper detail. I have updated the codes. Now you can specify the cfgs of stage 2 to decide whether to perform collision detection. Actually, we conduct both experiments, and the difference is not very obvious because collisions do not happen very often.

**Comment by YanWang-AI** [comment]
> Hello, thanks for your great work. I found some differences between the code and paper. According to the paper, "before merging the 3D boxes, collision detection will be performed". But in the intra_domain_point_mixup function, the "gt_boxes" were merged directly. This may cause some problems.

Thank you for your attention to the paper detail. I have updated the codes. Now you can specify the cfgs of stage 2 to decide whether to perform collision detection. Actually, we conduct both experiments, and the difference is not very obvious because collisions do not happen very often.

**Comment by AGI-player** [comment]
> > Hello, thanks for your great work. I found some differences between the code and paper. According to the paper, "before merging the 3D boxes, collision detection will be performed". But in the intra_domain_point_mixup function, the "gt_boxes" were merged directly. This may cause some problems.
> 
> Thank you for your attention to the paper detail. I have updated the codes. Now you can specify the cfgs of stage 2 to decide whether to perform collision detection. Actually, we conduct both experiments, and the difference is not very obvious because collisions do not happen very often.

ok, thanks.
