### ISSUE TITLE
Question about the nusc metric 

### ISSUE THREAD

**Issue by sky-fly97** [yinjunbo/SSDA3D#4]
Hi, are the **map/nds** results you reported for nusc a direct multiplication by 10 on top of the original metric?

Also it seems that there is no comparison with the results of source only + labeled target data （finetune）?

**Comment by YanWang-AI** [comment]
> Hi, are the **map/nds** results you reported for nusc a direct multiplication by 10 on top of the original metric?
> 
> Also it seems that there is no comparison with the results of source only + labeled target data （finetune）?

For the first question, we reported the ap and nds on car category only. 

For the second question, we didn’t compare with finetune. Actually we divided nuscenes into labeled and unlabeled based on frames in the final version of our paper. However, in the first version we divided according to scenes and we conducted the finetune experiments. Our method can surpass that by ~4%.
