### ISSUE TITLE
ST3D-UDA and ST3D-SSDA Comparison

### ISSUE THREAD

**Issue by c7huang** [yinjunbo/SSDA3D#5]
Hi, thanks for sharing the code for your project!

In the paper there are comparisons with ST3D in both UDA and SSDA settings. I have a few questions about these experiments.
* Since this repository does not seem to contain code related to ST3D, did you modify the official ST3D release to use CenterPoint?
* For waymo->nuscenes experiments, the ST3D configuration has pseudo-label updates disabled (`UPDATE_PSEUDO_LABEL_INTERVAL=1000`), were you using the same settings as them?

**Comment by YanWang-AI** [comment]
> 



> Hi, thanks for sharing the code for your project!
> 
> In the paper there are comparisons with ST3D in both UDA and SSDA settings. I have a few questions about these experiments.
> 
> * Since this repository does not seem to contain code related to ST3D, did you modify the official ST3D release to use CenterPoint?
> * For waymo->nuscenes experiments, the ST3D configuration has pseudo-label updates disabled (`UPDATE_PSEUDO_LABEL_INTERVAL=1000`), were you using the same settings as them?

Thanks for your attention.
For the first question, the answer is yes. We conduct the experiments on CenterPoint using the same strategy as that in ST3D, and utilize more information compared with ST3D, e.g., point intensity and GT_SAMPLING. 
For the second question, the answer is also yes. In fact, we found that when adapting Waymo to nuScenes, it seems that ST3D didn't apply the newly proposed method in the paper. So we follow the official ST3D configurations. I hope this will help you.

**Comment by c7huang** [comment]
That makes sense. Thanks for the clarification!
