### ISSUE TITLE
setting under 100% labeled target

### ISSUE THREAD

**Issue by miaozhang97** [yinjunbo/SSDA3D#6]
Thanks for sharing this excellent work! Could you please share the details about how the 2nd stage works under 100% labeled target setting? In this case, there will be no TU data, will the student-teacher learning still be conducted? Thanks in advance!

**Comment by YanWang-AI** [comment]
Sorry for the late response. We just fine-tune the model using GT labels after training Stage-1 for 100% labeled target setting.

**Comment by miaozhang97** [comment]
> Sorry for the late response. We just fine-tune the model using GT labels after training Stage-1 for 100% labeled target setting.

Got it. Thanks!
