### ISSUE TITLE
How did you generate the partial_info_data

### ISSUE THREAD

**Issue by fdy61** [yinjunbo/SSDA3D#7]
How did you generate the partial_info_data (1%, 5%, 10%, 20%)? For example, for the 1% data, did you take the first 1% of the info from the complete info.pkl file and split it into the top 1% and the last 99% of the pkl file? Or did you randomly sample 1% of the total amount of samples?

**Comment by yinjunbo** [comment]
Hi, we uniformly downsampled the data in a frame level, like
data[::interval]

**Comment by fdy61** [comment]
Thanks.  And What are the versions of TensorFlow and waymo-open-dataset-tf you are using? Also, what are your Python and PyTorch versions? I am encountering difficult environment issues.

**Comment by YanWang-AI** [comment]
> Thanks. And What are the versions of TensorFlow and waymo-open-dataset-tf you are using? Also, what are your Python and PyTorch versions? I am encountering difficult environment issues.

Hello. Sorry for the late response. This project was done during my internship at Inceptio and I finished the internship at 2023, so I couldn't check the exact environment anymore. But I remember that the OpenPCDet version was v0.5.2, maybe you can check the Readme of OpenPCDet v0.5.2 to reconstruct the environment. What's more, there is a difference in the channel permutation between SpConv 1.x and 2.x which may cause the pretrained weights unable to load. Hope this can help you.

**Comment by fdy61** [comment]
Thank you. I have solved it before.
