### ISSUE TITLE
where is the NDS score for car only?

### ISSUE THREAD

**Issue by fdy61** [yinjunbo/SSDA3D#8]
I have seen that the nds score reported is for all the categories, not for the car only.

**Comment by YanWang-AI** [comment]
> I have seen that the nds score reported is for all the categories, not for the car only.

Actually, the reported NDS is just calculated on the car only, because we only detect the car category.

**Comment by fdy61** [comment]
Is multiplying the resulting NDS by 10 the way to obtain the NDS result for cars? This is because the 10 classes in nuScenes only considered cars.
![image](https://github.com/user-attachments/assets/87c15bbe-f14e-4ee3-98cb-4c3c8146762e)

**Comment by YanWang-AI** [comment]
> Is multiplying the resulting NDS by 10 the way to obtain the NDS result for cars? This is because the 10 classes in nuScenes only considered cars. ![image](https://private-user-images.githubusercontent.com/134828384/348586645-87c15bbe-f14e-4ee3-98cb-4c3c8146762e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTA1NjYsIm5iZiI6MTcyMTAxMDI2NiwicGF0aCI6Ii8xMzQ4MjgzODQvMzQ4NTg2NjQ1LTg3YzE1YmJlLWYxNGUtNGVlMy05OGNiLTRjM2M4MTQ2NzYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMjI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU2MTA0OTk5MmU3MDIzNzU2MzQ3NzI0NmJhYjg0Njk0OTYxYjNkMDY5Zjg0OTZjYjQ0NTYzNjhlNGUxNmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SinIrB3yWOoKy-w2JdIOetwCmcbyILtxtFYObMxIDoI)

Exactly.

**Comment by fdy61** [comment]
That helps a lot. Thank you very much!
